name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy the app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
          port: ${{ secrets.DIGITALOCEAN_PORT }}
          script: |
            echo "ğŸ” Switching to app directory..."
            cd ~/chatchef_dir/chatchef-backend

            echo "ğŸ“¥ Pulling latest changes from main..."
            git stash
            git pull origin main

            echo "ğŸ Activating virtual environment..."
            source venv/bin/activate

            echo "ğŸ“¦ Installing dependencies..."
            pip install -r requirements.txt

            echo "ğŸ›  Running database migrations..."
            python manage.py migrate --no-input

            # Optional: Uncomment if you're using Django static files
            # echo "ğŸ“ Collecting static files..."
            # python manage.py collectstatic --no-input

            echo "ğŸš€ Restarting Gunicorn service..."
            sudo systemctl restart gunicorn_chatchef

            echo "âœ… Deployment to server completed."
